name: yaz_server_api
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'


dependencies:
  path: ^1.7.0
  args: ^1.6.0
  cryptography: ^1.4.1
  dio: ^3.0.10
  http: ^0.12.2
  image: ^2.1.19
  meta: ^1.2.4
  mongo_dart: ^0.4.4

dev_dependencies:
  effective_dart: any
  pedantic: ^1.9.2
  test: ^1.15.7
