name: yaz_server_api
description: Yaz Framework Api For Dart Server
version: 0.0.6+18
homepage: https://github.com/Mehmetyaz/yaz_client.git
repository: https://github.com/Mehmetyaz/yaz_client.git

environment:
  sdk: ">=2.15.0 <3.0.0"


dependencies:
  mailer: ^5.1.0
  path: ^1.8.1
  #args: ^1.6.0
  cryptography: ^2.0.5
  http: ^0.13.4
#  image: ^3.0.1
  meta: ^1.7.0
  mongo_dart: ^0.7.4
#  fixnum: ^0.10.8
#  bson: ^0.3.4


#dependency_overrides:
#  crypto: ^3.0.0
#  bson: ^0.3.4
#  fixnum: ^0.10.8
#  http: ^0.12.2

dev_dependencies:
  effective_dart: any
  test: ^1.20.1
